"""Construct CBOR inputs for scenarios, canonical and deliberately not.

The suite builds its own bytes rather than asking the implementation to
produce them. A fixture generated by the code under test cannot demonstrate
that the code rejects what it should: the defect and the fixture would
share the same mistake.
"""

from __future__ import annotations

import hashlib
import base64
import unicodedata


def cid_of(data: bytes, alg: str = "sha2-256") -> str:
    """Compute a CID independently of the implementation."""
    if alg != "sha2-256":
        raise ValueError(f"unsupported algorithm: {alg}")
    digest = hashlib.sha256(data).digest()
    return "pub:sha2-256:" + base64.b32encode(digest).decode().lower().rstrip("=")


def head(major: int, arg: int) -> bytes:
    """Encode a CBOR head using the shortest form."""
    m = major << 5
    if arg <= 23:
        return bytes([m | arg])
    if arg <= 0xFF:
        return bytes([m | 24, arg])
    if arg <= 0xFFFF:
        return bytes([m | 25]) + arg.to_bytes(2, "big")
    if arg <= 0xFFFFFFFF:
        return bytes([m | 26]) + arg.to_bytes(4, "big")
    return bytes([m | 27]) + arg.to_bytes(8, "big")


def text(s: str) -> bytes:
    raw = unicodedata.normalize("NFC", s).encode()
    return head(3, len(raw)) + raw


def uint(n: int) -> bytes:
    return head(0, n)


def cbor_map(pairs: list[tuple[str, bytes]]) -> bytes:
    """Encode a map, sorting keys by UTF-8 bytes as the profile requires."""
    ordered = sorted(pairs, key=lambda kv: kv[0].encode())
    out = head(5, len(ordered))
    for key, value in ordered:
        out += text(key) + value
    return out


# A key object CID used as `author` throughout the scenarios.
EXAMPLE_AUTHOR = cid_of(b"example key object")


def minimal_object(kind: str = "publet", created: str = "2026-09-12T10:00:00Z") -> bytes:
    """A well-formed object with an empty body."""
    return cbor_map([
        ("pub", text("1")),
        ("type", text(kind)),
        ("created", text(created)),
        ("author", text(EXAMPLE_AUTHOR)),
        ("body", cbor_map([])),
    ])


# Each entry is a Gherkin `defect` label mapped to bytes violating exactly
# that rule, and the rule name the implementation must report.
DEFECTS: dict[str, tuple[bytes, str]] = {
    "a non-shortest integer": (bytes([0x18, 0x05]), "shortest-form integers"),
    "unsorted map keys": (
        head(5, 2) + text("b") + uint(1) + text("a") + uint(2),
        "sorted map keys",
    ),
    "a duplicate map key": (
        head(5, 2) + text("a") + uint(1) + text("a") + uint(2),
        "unique map keys",
    ),
    "an indefinite-length array": (bytes([0x9F, 0x01, 0xFF]), "no indefinite length"),
    "a float value": (bytes([0xFA, 0x3F, 0x80, 0x00, 0x00]), "no floating point"),
    "text in NFD": (
        head(3, len("é".encode())) + "é".encode(),
        "NFC normalization",
    ),
    "a non-text map key": (head(5, 1) + uint(1) + uint(2), "text map keys"),
    "invalid UTF-8": (bytes([0x62, 0xFF, 0xFE]), "valid UTF-8"),
    "a CBOR tag": (bytes([0xC0, 0x01]), "supported item types"),
    "trailing data": (bytes([0x01, 0x02]), "single top-level item"),
}


# --- graph fixtures --------------------------------------------------------

def author_key(seed: str) -> str:
    """A stable pseudo-key identifier for a named participant."""
    return cid_of(seed.encode())


def obj(kind: str, author: str, created: str, body: list[tuple[str, bytes]]) -> bytes:
    return cbor_map([
        ("pub", text("1")),
        ("type", text(kind)),
        ("created", text(created)),
        ("author", text(author)),
        ("body", cbor_map(body)),
    ])


def publet(author: str, created: str, cls: str, content: str,
           depends: list[str] | None = None) -> bytes:
    body = [
        ("class", text(cls)),
        ("lang", text("en")),
        ("content", text(content)),
    ]
    deps = depends or []
    body.append(("depends", head(4, len(deps)) + b"".join(text(d) for d in deps)))
    return obj("publet", author, created, body)


def relation(author: str, created: str, kind: str, frm: str, to: str) -> bytes:
    return obj("rel", author, created, [
        ("kind", text(kind)),
        ("from", text(frm)),
        ("to", text(to)),
    ])


def annotation(author: str, created: str, kind: str, target: str,
               aspect: str | None = None) -> bytes:
    body = [("kind", text(kind)), ("target", text(target))]
    if aspect is not None:
        body.append(("aspect", text(aspect)))
    return obj("ann", author, created, body)


def write_store(directory, objects: list[bytes]) -> dict[str, str]:
    """Write objects into a directory, named by their identifier.

    Returns a map from CID to filename so scenarios can refer to either.
    """
    out = {}
    for data in objects:
        cid = cid_of(data)
        name = cid.replace(":", "_") + ".cbor"
        (directory / name).write_bytes(data)
        out[cid] = name
    return out
