#!/usr/bin/env bash
# Regenerate tests/requirements.lock with pinned versions and sha256 hashes.
set -euo pipefail
cd "$(dirname "$0")/.."
source tools/env.sh
report="$(mktemp)"
trap 'rm -f "$report"' EXIT
python -m pip install --dry-run --ignore-installed --report "$report" -q \
  -r tests/requirements.txt >/dev/null
python - "$report" <<'PY'
import json, sys
report = json.load(open(sys.argv[1]))
out = ["# Generated by `make lock` from tests/requirements.txt. Do not edit.",
       "# Installed with --require-hashes: a changed artifact fails the build.",
       ""]
for item in sorted(report["install"], key=lambda i: i["metadata"]["name"].lower()):
    name = item["metadata"]["name"]
    version = item["metadata"]["version"]
    digest = item["download_info"]["archive_info"]["hashes"]["sha256"]
    out.append(f"{name}=={version} \\\n    --hash=sha256:{digest}")
open("tests/requirements.lock", "w").write("\n".join(out) + "\n")
print(f"locked {len(report['install'])} packages")
PY
